# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Shapfile AddEditInfo & rename
# "for" loop
# ListDatasets.py
# AddField.py
# Calculated.py
# Rename.py
# Created on: 2021-04-09 11:14:09.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
import os

# Set path.
path = "D:\\OSM\\Europe\\Poland\\"

# Make location to a list.
file_L = os.listdir(path)

# Use "For Loop" run all the location under list path file.
for location_in_lower in file_L:
    # location title Upper.
    location_name = location_in_lower.title()
    print(location_name)
    arcpy.env.workspace = path + location_in_lower + "\\"

    # Until "work_File" is "Get all Shp. file under this path."
    # After "if" is "Set AddField."
    datasets1 = arcpy.ListDatasets(feature_type='feature')
    datasets2 = [''] + datasets1 if datasets1 is not None else []

    try:
        for ds in datasets2:
            for fc in arcpy.ListFeatureClasses(feature_dataset=ds):
                work_F = os.path.join(arcpy.env.workspace, ds, fc)           
                if arcpy.Exists(work_F):
                    # Field title named "location"
                    arcpy.AddField_management(work_F, "location", "TEXT", "", "",  30, "", "NULLABLE")
                    # Calculated name is "location name" which is same file location name. Notice "quotation mark" !!!
                    arcpy.CalculateField_management(work_F, "location", '"' + location_name + '"' , "PYTHON", "")
                    print location_name + "_" + fc + " fields are added."

    except:
        print location_name + "_" + fc + " error."


    
    #rename Shp.
    in_data_railway = "gis_osm_railways_free_1.shp"
    out_data_railway = location_name + "_railway.shp"

    in_data_road = "gis_osm_roads_free_1.shp"
    out_data_road = location_name + "_road.shp"

    data_type = "FeatureClass"

    arcpy.Rename_management(in_data_railway, out_data_railway, data_type)
    arcpy.Rename_management(in_data_road, out_data_road, data_type)
    print location_name + " railway and road are renamed."   

print "Finished."
