# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Make Feature Layer.py
# Select Layer By Attribute.py
# Append.py
# "for" loop and "if, else"
# Can run all layer in one geodatabase.
# Regonize railway and road layer.
# Created on: 2021-07-04 15:00:09.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
import os

# Set path.
arcpy.env.workspace = "D:\\ArcMap test\\Select_try.gdb\\"
arcpy.env.overwriteOutput = True

# Select railway & road table by SQL.
railway_select = "fclass in ('funicular', 'light_rail', 'monorail', 'narrow_gauge', 'rail', 'subway', 'tram')"
road_select = "fclass in ('motorway')"

# Get all contents in GDB.
datasets1 = arcpy.ListDatasets(feature_type='feature')
datasets2 = [''] + datasets1 if datasets1 is not None else []

for ds in datasets2:
    for fc in arcpy.ListFeatureClasses(feature_dataset=ds):
        transform = os.path.join(arcpy.env.workspace, ds, fc)

        railway = "_railway"

        if railway in transform:
            # Select railway row.
            arcpy.MakeFeatureLayer_management(transform, "transform_layer")
            arcpy.SelectLayerByAttribute_management("transform_layer", "NEW_SELECTION", railway_select)
            # Append select railway row to new GDB.
            railway_target_path = "D:\\ArcMap test\\Append_try.gdb\\"
            railway_emptyFC = "Germany_railway"
            schemaType = "No_TEST"
            arcpy.Append_management("transform_layer", railway_target_path + railway_emptyFC, schemaType, "", "")
            print (transform + " select features are Append.")

        else:
            # Select road row.
            arcpy.MakeFeatureLayer_management(transform, "transform_layer")
            arcpy.SelectLayerByAttribute_management("transform_layer", "NEW_SELECTION", road_select)
            # Append select road row to new GDB.
            road_target_path = "D:\\ArcMap test\\Append_try.gdb\\"
            road_emptyFC = "Germany_road"
            schemaType = "No_TEST"
            arcpy.Append_management("transform_layer", road_target_path + road_emptyFC, schemaType, "", "")
            print (transform + " select features are Append.")

print "Finished."