# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Calculate Min&Max XY coordinate
# AddField.py
# Calculated.py
# Created on: 2021-06-23 15:47:39.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Set path.
workpath = "D:\\ArcMap test\\Country.gdb\\"
inFeatures = workpath + "Ausin_BoundingGe\\"

# Set coordinate and Title of table
infield1 = "XMax"
infield2 = "XMin"
infield3 = "YMax"
infield4 = "YMin"
fieldPrecision = "18"
fieldScale = "11"

# AddField Title
arcpy.AddField_management(inFeatures, infield1, "DOUBLE", fieldPrecision, fieldScale)
arcpy.AddField_management(inFeatures, infield2, "DOUBLE", fieldPrecision, fieldScale)
arcpy.AddField_management(inFeatures, infield3, "DOUBLE", fieldPrecision, fieldScale)
arcpy.AddField_management(inFeatures, infield4, "DOUBLE", fieldPrecision, fieldScale)
# Calculate coordinate
arcpy.CalculateField_management(inFeatures, infield1, "!SHAPE.EXTENT.XMin!", "PYTHON_9.3")
arcpy.CalculateField_management(inFeatures, infield2, "!SHAPE.EXTENT.YMin!", "PYTHON_9.3")
arcpy.CalculateField_management(inFeatures, infield3, "!SHAPE.EXTENT.YMax!", "PYTHON_9.3")
arcpy.CalculateField_management(inFeatures, infield4, "!SHAPE.EXTENT.YMin!", "PYTHON_9.3")

print "Finished!"